# Generated by Django 4.1.6 on 2023-02-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_onemoretitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="onemoretitle",
        ),
        migrations.AddField(
            model_name="blog",
            name="date",
            field=models.DateField(auto_now=True),
        ),
    ]
