# Generated by Django 4.1.6 on 2023-02-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blog_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="text",
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
