# Generated by Django 4.1.6 on 2023-02-20 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_url_project_new name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="new name",
            new_name="url",
        ),
    ]
