# Generated by Django 4.1.6 on 2023-02-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_project_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="url",
            field=models.URLField(blank=True, verbose_name="text"),
        ),
    ]
